### ISSUE TITLE
[Task-front]final system

### ISSUE THREAD

**Issue by wjdghksdigh** [codestates-seb/seb43_main_019#120]
주재민  - images formdata 해결 , mypage 미디어쿼리 추가
오준석 - kakao payment 해결
김정환 - map swipe ,  detail , review css 수정

공통 - folder repactoring (폴더 앞 대문자 , 공통 컴포넌트 수정 , ... )

해결한 결과와 코드를 댓글로 공유해주세요!🙂

**Comment by JS2L** [comment]
확인 했습니다!

**Comment by als982001** [comment]
확인했습니다

**Comment by als982001** [comment]
상품 등록 해결했어요 🕺

**Comment by als982001** [comment]
mypage 미디어 쿼리 추가
