### ISSUE TITLE
[Debate] 소셜로그인 토큰을 다루는 위치에 대해

### ISSUE THREAD

**Issue by als982001** [codestates-seb/seb43_main_019#55]
API 명세서의 로그인 부분에서, response로 토큰 값을 준다고 나와 있습니다. 이럴 경우 토큰 값을 프론트 쪽에서 다루게 되는데, 이는 보안 상으로 좋지 않다고 합니다. 그래서 이 부분에 대해 이야기를 나누고 싶습니다.
이 부분에 대해 chatGPT에 물어본 결과, 다음과 같이 답을 해줬습니다.
***
일반적으로 프론트엔드에서 액세스 토큰(access token)과 리프레시 토큰(refresh token)을 직접 다루는 것은 권장되지 않습니다. 대부분의 경우 백엔드 서버에서 토큰을 발급하고 관리하며, 프론트엔드는 토큰을 받아 백엔드 API에 접근하는 역할을 합니다.

프론트엔드에서 토큰을 다루는 것은 보안 문제로 이어질 수 있기 때문입니다. 액세스 토큰과 리프레시 토큰은 중요한 정보를 담고 있으며, 악의적인 공격자에게 탈취당할 경우 보안 상의 문제가 발생할 수 있습니다.

따라서 보통은 백엔드 서버에서 토큰을 발급하고, 해당 토큰을 프론트엔드로 전송합니다. 이후 프론트엔드는 해당 토큰을 저장하고 백엔드 API에 접근할 때마다 해당 토큰을 전송하여 인증을 수행합니다.

**Comment by exertivestar** [comment]
멘토님 답변

<aside>
2️⃣ 보안적으로 탄탄하게 하려면 토큰을 쿠키에 담아서 쿠키옵션을 줄 수 있다. 
우리는 보안 신경 안쓰겠다고 하면 엑세스토큰과 리프레시토큰 둘 다 클라이언트에게 응답으로 줘도 괜찮다.
보통은 리프레시토큰은 서버에서 보관을 한다고해도 클라이언트에서 리프레시 토큰이랑 매핑될 수 있는 정보를 가지고 있어야 한다.

http 올리랑 시큐어 이라는 옵션을 줄 수가 있어요.

http 올리 같은 경우는 자바스크립트로 접근 못하게 막고 cq 같은 경우는 htps로만 통신하겠다.

이런 거거든요. 그러니까 이제 자바스크립트로 접근을 못하게 해서 xss 방지하고

이제 htps로만 통신해가지고 암호화해가지고 보내겠다. 이렇게 하면 조금 더 안전하게 관리를 할 수가 있어요. 그래서 리프레시 토큰 같은 경우에는 어쨌든 서버에서 들고는 있어야 돼요 어떤 유저의 리프레시 토큰이 이게 맞는지 확인을 해야 돼가지고 서버에서 무조건

갖고는 있어야 돼요 어디서든가 db rdb에 저장을 하거나 조금 더 빠르게 하시겠다. 이러면 요즘에는 redis 같은 데다가 저장을 하기는 하는데 그거는 이제 개인의 선택이고 지금 같이 트래픽이 없는 경우에는 그냥 간단하게 db에다가 저장을 하시면 되겠죠.

프론트 단과 데이터를 주고받을 때 사실 리프레시 토큰 같은 경우는 프론트에서 굳이 그 값을 알 필요는 없거든요.

그래서 그냥 엑세스 토큰 같은 경우에는 간단하게 응답이죠.

그냥 http 리스폰스 응답으로 내려주면 되고 리프레시 같은 경우에는 방금 말씀드렸던 것처럼 그냥 쿠키에다 담아서 주셔도 괜찮아요.

</aside>

**Comment by SHyeonCoding** [comment]
사용자 인증과 권한 부여를 위해 백엔드에서 처리하는 것이 맞는 것 같습니다. 
토큰 값은 헤더에 담아서 보내는걸로 하겠습니다.

**Comment by als982001** [comment]
네 알겠습니다.
이를 바탕으로 다시 해보겠습니다.
