### ISSUE TITLE
[Task-Front] clean code - common

### ISSUE THREAD

**Issue by wjdghksdigh** [codestates-seb/seb43_main_019#75]
<h2>[clean code 관련]</h2>

<h3>공통으로 들어가는 컴포넌트 : button, input, modal, ...</h3>

공통으로 들어가는 컴포넌트를 새로 생성하지 마시고 common 폴더에 있는 컴포넌트를
꼭 import 해주세요 ! 불필요한 코드를 줄여주세요!
만약 새로 생성하고 싶은 디자인이 있다면 common 폴더에 생성하시고 export해주세요.

<br>
<h3>
사용 예시
</h3>

<img width="470" alt="스크린샷 2023-05-16 오전 12 10 02" src="https://github.com/codestates-seb/seb43_main_019/assets/78897615/d7281aa6-4305-412e-be2b-4ca3b5a448fd">

**Comment by als982001** [comment]
완료
